### ISSUE TITLE
Perfect  Job ,  Tidy code  & Pretty Style  , I have small note only

### ISSUE THREAD

**Issue by mahmoudaboc** [meyadd/hyf-javascript2#1]
- I see appendChild  all together  near the end of code , maybe its better to write it after createElement
I think it easy  to read the code 

https://github.com/meyadd/hyf-javascript2/blob/eb14c7c73657da0a1901a16a48f7f1bf20951215/week1/script.js#L2892

**Comment by meyadd** [comment]
Thank you for your note
